on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          packager: npm
      - name: Install dependencies
        run: npm ci
      - name: Build and publish apk
        run: eas build -p android --profile apk
      - name: Download published apk
        run: eas build:list --json --limit=1 --platform=android | jq '.[0].artifacts.buildUrl' | xargs wget -O ${{ github.event.repository.name }}-${{ github.ref_name }}.apk
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.event.repository.name }}-${{ github.ref_name }}.apk